language: rust

rust:
  - stable
  - nightly

cache: cargo

before_script:
  - cargo install rustfmt --vers 0.9.0
  - cargo install clippy --vers 0.0.166

script:
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose
  - cargo test --verbose
  - cargo clippy --profile=test
