language: rust

rust:
  - stable
  - nightly
  - nightly-2017-10-22

cache: cargo

before_script:
  - sudo apt-get install -y cmake g++ pkg-config libcurl4-openssl-dev libdw-dev
    binutils-dev libiberty-dev
  - cargo install rustfmt --vers 0.9.0 --force
  - cargo install cargo-kcov --vers 0.4.2 --force
  - cargo kcov --print-install-kcov-sh | sh
  - if [ "${TRAVIS_RUST_VERSION}" = nightly-2017-10-22 ]; then
      (
        set -x;
        cargo install clippy --vers 0.0.166 --force
      );
    fi

script:
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose
  - cargo kcov --verbose
  - cargo kcov --coveralls --verbose
  - if [ "${TRAVIS_RUST_VERSION}" = nightly-2017-10-22 ]; then
      (
        set -x;
        cargo clippy --profile=test
      );
    fi
